services:

  broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: '${COMPOSE_PROJECT_NAME:-pmd}-broker'
    ports:
      - '${PORT_BROKER:-29092}:29092'
    volumes:
      - broker-data:/var/lib/kafka/data
    environment:
      CLUSTER_ID: '${CLUSTER_ID:-YzUyZWRlYzBhNDkwNDNmNG}'
      KAFKA_NODE_ID: '1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'INTERNAL://broker:9092,EXTERNAL://broker:29092,CONTROLLER://broker:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://broker:9092,EXTERNAL://localhost:${PORT_BROKER:-29092}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: '1'
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: '1'
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_LOG4J_ROOT_LOGLEVEL: 'WARN'
      KAFKA_LOG4J_LOGGERS: "\
        kafka=WARN,\
        kafka.controller=WARN,\
        kafka.log.LogCleaner=WARN,\
        state.change.logger=WARN,\
        kafka.producer.async.DefaultEventHandler=WARN"

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: '${COMPOSE_PROJECT_NAME:-pmd}-kafka-ui'
    ports:
      - '${PORT_KAFKA_UI:-28080}:8080'
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_0_NAME: 'thesis-project'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'broker:9092'
      LOGGING_LEVEL_ROOT: 'ERROR'
      LOGGING_LEVEL_COM_PROVECTUS: 'WARN'
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: 'http://schemaregistry:8085'

  schemaregistry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schemaregistry
    depends_on:
      - broker
    ports:
      - '${PORT_SCHEMA_REGISTRY:-8085}:8085'
    environment:
      SCHEMA_REGISTRY_LISTENERS: 'http://schemaregistry:8085'
      SCHEMA_REGISTRY_HOST_NAME: 'schemaregistry'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://broker:9092'
      SCHEMA_REGISTRY_DEBUG: 'true'

  producer:
    build: producer
    image: '${COMPOSE_PROJECT_NAME:-pmd}-producer:latest'
    container_name: '${COMPOSE_PROJECT_NAME:-pmd}-producer'
    env_file: .env
    environment:
      - EVENT_LOG
    depends_on:
      - broker
    profiles:
      - producer
    volumes:
      - ./experiments/data:/experiments/data
    command: [ '--bootstrap-server', 'broker:9092', '--schema-registry-url', 'http://schemaregistry:8085' ]

  frontend:
    build: frontend
    image: '${COMPOSE_PROJECT_NAME:-pmd}-frontend:latest'
    container_name: '${COMPOSE_PROJECT_NAME:-pmd}-frontend'
    depends_on:
      - broker
    ports:
      - '${PORT_FRONTEND:-8888}:8888'
    volumes:
      - ./frontend/src:/frontend/src
    command: [ '--', '--bootstrap-servers', 'broker:9092', '--graphviz-declare',  '/frontend/src' ]

volumes:
  broker-data:
  graphviz-declare: